// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drsyoiwywdycqrovaain.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyc3lvaXd5d2R5Y3Fyb3ZhYWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDI2MzQsImV4cCI6MjA1NzI3ODYzNH0.T4FPHFY02pRqcLxKN-UUmGIPiuqn0zOfBsGzqBzFDrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);